/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFEmpleado;


import Fuentes.Conexion;
import JFrameLogin.JFIngreso;
import Módulo.JFModuloAdmi;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN
 */
public class JFActualizarEmpleado extends javax.swing.JFrame {
    private Conexion conexion ;
    /**
     * Creates new form JFEmpleado
     */
    public JFActualizarEmpleado() {
        initComponents();
        conexion =  new Conexion("Equimeta", "123");
        conexion.crearConexion();
        this.setLocationRelativeTo(null);
        this.jCBEstadoCivil.setEnabled(false);
        this.jTFApellidos.setEnabled(false);
        this.jTFCargo.setEnabled(false);
        this.jTFDireccion.setEnabled(false);
        this.jTFFecha.setEnabled(false);
        this.jTFSueldo.setEnabled(false);
        this.jTFInstruccion.setEnabled(false);
        this.jTFTelefono.setEnabled(false);
        this.jBActualizar.setVisible(false);
        this.jBNuevo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jDialog1 = new javax.swing.JDialog();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFCedula = new javax.swing.JTextField();
        jTFApellidos = new javax.swing.JTextField();
        jTFFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCBEstadoCivil = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jTFDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFCargo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFSueldo = new javax.swing.JTextField();
        jTFInstruccion = new javax.swing.JTextField();
        jBActualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MÓDULO EMPLEADO");

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("INICIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("MÓDULOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        jLabel2.setText("Nombres y Apellidos");

        jLabel3.setText("Fecha de Nacimiento:");

        jLabel4.setText("Sueldo:");

        jLabel5.setText("Número de cédula:");

        jLabel6.setText("Dirección Domiciliaria:");

        JTFCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCedulaActionPerformed(evt);
            }
        });

        jTFApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFApellidosActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado Civil:");

        jCBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar una opciòn", "Soltero", "Casado", "Viudo", "Divorciado", "Unión Libre" }));
        jCBEstadoCivil.setToolTipText("");
        jCBEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadoCivilActionPerformed(evt);
            }
        });

        jLabel9.setText("Teléfono:");

        jLabel10.setText("Cargo");

        jLabel11.setText("Instrucción:");

        jTFInstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFInstruccionActionPerformed(evt);
            }
        });

        jBActualizar.setText("ACTUALIZAR");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("ACTUALIZAR EMPLEADO");

        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBNuevo.setText("NUEVO");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(272, 272, 272))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFInstruccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(98, 98, 98)
                                .addComponent(jTFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(JTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBAceptar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAceptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jTFInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jMenu1.setText("Menú");

        jMenuItem1.setText("Registrar Empleado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Actualizar Empleado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Consultar Empleado");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Empleado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFConsultarEmpleado jfConsultar = new JFConsultarEmpleado();
        jfConsultar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFRegistrarEmpleado jfRegistrar = new JFRegistrarEmpleado();
        jfRegistrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFEliminarEmpleado jfEliminar = new JFEliminarEmpleado();
        jfEliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFModuloAdmi jfModulo = new JFModuloAdmi();
        jfModulo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFActualizarEmpleado jfActualizar=new JFActualizarEmpleado();
        jfActualizar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JTFCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCedulaActionPerformed

    private void jCBEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEstadoCivilActionPerformed

    private void jTFInstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFInstruccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFInstruccionActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
     Pattern pat = Pattern.compile("[0-9]{10}");
     Matcher mat = pat.matcher(this.JTFCedula.getText());
     if(JTFCedula.getText().length()>0){
           if (mat.matches()) {
               if(conexion.existeRegistro("Empleado", "NUMCEDULA = '"+this.JTFCedula.getText()+"'")==true){
                   this.jTFApellidos.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","NOMBRECOMPLETOS"));
                   this.jTFDireccion.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","DIRECCIONEMPLEADO"));
                   this.jTFTelefono.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","TELEFONO_EMPLEADO"));
                   this.jTFInstruccion.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","INSTRUCCION"));
                    this.jTFCargo.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","SUELDO"));
                    this.jTFSueldo.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","SUELDO"));
                    this.jTFFecha.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","FECHANACIMIENTO"));
                    this.jTFInstruccion.setText(conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","INSTRUCCION"));
                    String Civil = conexion.obtenerRegistro("Empleado", "NUMCEDULA = '"+JTFCedula.getText()+"'","ESTADOCIVIL");
                    if(Civil.compareToIgnoreCase("Soltero")==0){
                            this.jCBEstadoCivil.setSelectedItem("Soltero");
                    }
                    if(Civil.compareToIgnoreCase("Casado")==0){
                            this.jCBEstadoCivil.setSelectedItem("Casado");
                    }
                    if(Civil.compareToIgnoreCase("Viudo")==0){
                            this.jCBEstadoCivil.setSelectedItem("Viudo");
                    }
                    if(Civil.compareToIgnoreCase("Divorciado")==0){
                            this.jCBEstadoCivil.setSelectedItem("Divorciado");
                    }
                    if(Civil.compareToIgnoreCase("Unión Libre")==0){
                            this.jCBEstadoCivil.setSelectedItem("Unión Libre");
                    }
                    this.JTFCedula.setEnabled(false);
                    this.jTFTelefono.setEnabled(true);
                    this.jTFDireccion.setEnabled(true);
                    this.jBActualizar.setVisible(true);
                    this.jBNuevo.setVisible(true);
                    this.jTFApellidos.setVisible(true);
                    this.jBAceptar.setVisible(false);
               }else{
               JOptionPane.showMessageDialog(rootPane, "El Empleado no existe");
               }
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Se ha ingresado erróneamente el nùmero de cèdula");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "El campo se encuentra vacìo");
     }

        this.JTFCedula.setEnabled(false);
        this.jCBEstadoCivil.setEnabled(true);
        this.jTFApellidos.setEnabled(true);
        this.jTFCargo.setEnabled(true);
        this.jTFDireccion.setEnabled(true);
        this.jTFFecha.setEnabled(true);
        this.jTFSueldo.setEnabled(true);
        this.jTFInstruccion.setEnabled(true);
        this.jTFTelefono.setEnabled(true);
        this.jBActualizar.setVisible(true);
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        this.jCBEstadoCivil.setEnabled(false);
        this.jTFApellidos.setEnabled(false);
        this.jTFCargo.setEnabled(false);
        this.jTFDireccion.setEnabled(false);
        this.jTFFecha.setEnabled(false);
        this.jTFSueldo.setEnabled(false);
        this.jTFInstruccion.setEnabled(false);
        this.jTFTelefono.setEnabled(false);
        this.jBActualizar.setVisible(false);
         this.JTFCedula.setEnabled(true);
         this.jBNuevo.setVisible(false);
         this.jBAceptar.setVisible(true);
         this.JTFCedula.setText("");
         this.jTFApellidos.setText("");
         this.jTFCargo.setText("");
         this.jTFDireccion.setText("");
         this.jTFFecha.setText("");
         this.jTFInstruccion.setText("");
         this.jTFSueldo.setText("");
         this.jTFTelefono.setText("");
         this.jCBEstadoCivil.setSelectedIndex(-1);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
                Pattern pat = Pattern.compile("[0-9]{10}");
            Matcher mat = pat.matcher(this.JTFCedula.getText());
            Matcher mat1 = pat.matcher(this.jTFTelefono.getText());
            if(jTFTelefono.getText().length()>0 && JTFCedula.getText().length()>0 && jTFApellidos.getText().length()>0 && this.jTFApellidos.getText().length()>0 &&
                     jTFFecha.getText().length()>0 && jTFCargo.getText().length()>0 &&  jTFDireccion.getText().length()>0 && this.jTFSueldo.getText().length()>0 && 
                    this.jTFInstruccion.getText().length()>0 && jCBEstadoCivil.getSelectedIndex()!=0){
           if (mat.matches() && mat1.matches()) {
               if(conexion.existeRegistro("Empleado", "NUMCEDULA = '"+this.JTFCedula.getText()+"'")==true){                   
                   
                    conexion.modificarRegistro("Empleado","NOMBRECOMPLETOS ='"+jTFApellidos.getText()+"', TELEFONO_EMPLEADO= '"+jTFTelefono.getText()+"', DIRECCIONEMPLEADO = '"+jTFDireccion.getText()+"', ESTADOCIVIL ='"+jCBEstadoCivil.getSelectedItem()
                            +"',FECHANACIMIENTO = '"+jTFFecha.getText()+"', CARGO= '"+jTFCargo.getText()+"',Instruccion = '"+jTFInstruccion.getText()
                            +"',Sueldo= "+Float.parseFloat(this.jTFSueldo.getText())+"","NUMCEDULA = '"+JTFCedula.getText()+"'" );
                           JOptionPane.showMessageDialog(rootPane, "Informacion actualizada");
               }else{
               JOptionPane.showMessageDialog(rootPane, "El registro no existe");
               }
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Un dato ha sido ingresado erróneamente");                                                                       
     } 
     }else{
     JOptionPane.showMessageDialog(rootPane, "Ingrese datos en todos los campos");
     }
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFIngreso jfing = new JFIngreso();
        jfing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTFApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFApellidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFActualizarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFCedula;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCBEstadoCivil;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFCargo;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFInstruccion;
    private javax.swing.JTextField jTFSueldo;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
