
package JFCliente;

import Fuentes.AlgoritmoVerificar;
import Fuentes.Conexion;
import JFrameLogin.JFIngreso;
import Módulo.JFModuloAdmi;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN
 */
public class JFActualizarCliente extends javax.swing.JFrame {
    private Conexion conexion ;
    private AlgoritmoVerificar av;
    /**
     * Creates new form JFEmpleado
     */

    
    public JFActualizarCliente() {
        av = new AlgoritmoVerificar();
        conexion =  new Conexion("Equimeta", "123");
        conexion.crearConexion();
        initComponents();
        this.jBActualizar1.setVisible(false);
        this.jBNuevo1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.jTFCelular.setEnabled(false);
        this.jTFDireccion.setEnabled(false);
        this.jTFCelular1.setEnabled(false);
        this.jTFDireccion1.setEnabled(false);
        this.jTFRepresentanteLegal.setEnabled(false);
        this.jBActualizar.setVisible(false);
        this.jBNuevo.setVisible(false);
        this.jLabel1.setVisible(true);
        this.jTFNombre.setVisible(true);
       this.jTFNombre.setEnabled(false);
               this.jLabel4.setVisible(false);
                    this.jTFNombre1.setVisible(false);
                    this.jTFNombre1.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jDialog1 = new javax.swing.JDialog();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JTFCedula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFCelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JTFRUC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFDireccion1 = new javax.swing.JTextField();
        jTFCelular1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jBNuevo1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTFRepresentanteLegal = new javax.swing.JTextField();
        jBAceptar1 = new javax.swing.JButton();
        jBActualizar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MÓDULO CLIENTE");

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("INICIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("MÓDULOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Número de cédula:");

        JTFCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCedulaActionPerformed(evt);
            }
        });

        jLabel10.setText("Celular:");

        jTFCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCelularActionPerformed(evt);
            }
        });

        jLabel6.setText("Dirección Domiciliaria:");

        jTFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDireccionActionPerformed(evt);
            }
        });

        jBAceptar.setForeground(new java.awt.Color(204, 204, 204));
        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBActualizar.setText("ACTUALIZAR");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jBNuevo.setText("NUEVO");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Completo:");

        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(94, 94, 94)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(75, 75, 75)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(94, 94, 94)
                                .addComponent(JTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Persona Natural", jPanel2);

        jLabel7.setText("RUC:");

        JTFRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFRUCActionPerformed(evt);
            }
        });

        jLabel8.setText("Dirección:");

        jTFDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDireccion1ActionPerformed(evt);
            }
        });

        jTFCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCelular1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Celular:");

        jBNuevo1.setText("Nuevo");
        jBNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevo1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Representante Legal:");

        jTFRepresentanteLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRepresentanteLegalActionPerformed(evt);
            }
        });

        jBAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        jBAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptar1ActionPerformed(evt);
            }
        });

        jBActualizar1.setText("ACTUALIZAR");
        jBActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizar1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Completo de la Empresa:");

        jTFNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombre1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addComponent(jBNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTFNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(90, 90, 90)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTFRepresentanteLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JTFRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTFCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jBAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(153, 153, 153)
                                .addComponent(jTFDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JTFRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRepresentanteLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTFDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Persona Jurídica", jPanel3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("ACTUALIZAR CLIENTE");

        jMenu1.setText("Menú");

        jMenuItem1.setText("Registrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Consultar Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFConsultarCliente jfConsultar = new JFConsultarCliente();
        jfConsultar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFRegistrarCliente jfRegistrar = new JFRegistrarCliente();
        jfRegistrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFEliminarCliente jfEliminar = new JFEliminarCliente();
        jfEliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFModuloAdmi jfModulo = new JFModuloAdmi();
        jfModulo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JTFCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCedulaActionPerformed
        if(av.idCardEcuador(this.JTFCedula.getText())==false){
            JOptionPane.showMessageDialog(rootPane, "Cédula incorrecta");
        }
    }//GEN-LAST:event_JTFCedulaActionPerformed

    private void JTFRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFRUCActionPerformed
        if(this.JTFRUC.getText().length()>0 && this.JTFRUC.getText().length()<13){
        }else{
        JOptionPane.showMessageDialog(rootPane, "El RUC ingresado es incorrecto");
        }
    }//GEN-LAST:event_JTFRUCActionPerformed

    private void jBNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevo1ActionPerformed
        // TODO add your handling code here:
        this.JTFRUC.setText("");
        this.JTFRUC.setEnabled(true);
        this.jTFRepresentanteLegal.setText("");
        this.jTFRepresentanteLegal.setEnabled(false);
        this.jTFCelular1.setText("");
        this.jTFCelular1.setEnabled(false);
        this.jTFDireccion1.setText("");
        this.jTFDireccion1.setEnabled(false);
        this.JTFRUC.requestFocus();
                this.jBAceptar1.setVisible(true);
                this.jTFNombre1.setText("");
                                            this.jBActualizar1.setVisible(false);
                            this.jBNuevo1.setVisible(false);
    }//GEN-LAST:event_jBNuevo1ActionPerformed


    
    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        
        Pattern pat = Pattern.compile("[0-9]{10}");
     Matcher mat = pat.matcher(this.JTFCedula.getText());
     if(JTFCedula.getText().length()>0){
           if (mat.matches()) {
               if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFCedula.getText()+"'")==true){
                   this.jTFNombre.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFCedula.getText()+"'","NOMBRE"));
                   this.jTFDireccion.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFCedula.getText()+"'","DIRECCION"));
                    this.jTFCelular.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFCedula.getText()+"'","TELEFONO_CLIENTE"));
                    this.JTFCedula.setEnabled(false);
                    this.jTFCelular.setEnabled(true);
                    this.jTFDireccion.setEnabled(true);
                    this.jBActualizar.setVisible(true);
                    this.jBNuevo.setVisible(true);
                    this.jLabel1.setVisible(true);
                    this.jTFNombre.setVisible(true);
                    this.jTFNombre.setEnabled(false);
                    this.jBAceptar.setVisible(false);
               }else{
               JOptionPane.showMessageDialog(rootPane, "El cliente no existe");
               }
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Se ha ingresado erróneamente el nùmero de cèdula");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "El campo se encuentra vacìo");
     }
 
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jTFCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCelularActionPerformed
        if(this.jTFNombre.getText().length()>0 && this.jTFNombre.getText().length()<=30){    
     }else{
                            JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");
         
     }
    }//GEN-LAST:event_jTFCelularActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        Pattern pat = Pattern.compile("[0-9]{10}");
     Matcher mat1 = pat.matcher(this.jTFCelular.getText());
     if(jTFCelular.getText().length()>0 && jTFDireccion.getText().length()>0){
           if ( mat1.matches()) {
               if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFCedula.getText()+"'")==true){
            
                   conexion.modificarRegistro("Cliente","TELEFONO_CLIENTE= '"+jTFCelular.getText()+"', DIRECCION = '"+jTFDireccion.getText()+"'","ID_CLIENTE = '"+JTFCedula.getText()+"'" );
        JOptionPane.showMessageDialog(rootPane, "Informacion actualizada");               
               }else{
                        JOptionPane.showMessageDialog(rootPane, "El nùmero de cèdula del cliente ingresado no existe");
               }
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Un dato ha sido ingresado erróneamente");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "Ingrese datos en todos los campos");
     }
        
     

    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        this.jTFCelular.setText("");
        this.jTFCelular.setEnabled(false);
        this.jTFDireccion.setText("");
        this.jTFDireccion.setEnabled(false);
        this.jBActualizar.setVisible(false);
        this.JTFCedula.setText("");
        this.jTFNombre.setText("");
        this.JTFCedula.setEnabled(true);
        this.jBNuevo.setVisible(false);
        this.jLabel1.setVisible(true);
        this.jTFNombre.setVisible(true);
        this.jTFNombre.setEnabled(false);
        this.jBNuevo.setVisible(false);
                            this.jBAceptar.setVisible(true);
                            this.jBActualizar1.setVisible(false);
                            this.jBNuevo1.setVisible(false);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptar1ActionPerformed
        // TODO add your handling code here:        
        Pattern pat = Pattern.compile("[0-9]{13}");
     Matcher mat = pat.matcher(this.JTFRUC.getText());
     if(JTFRUC.getText().length()>0){
           if (mat.matches()) {
               if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFRUC.getText()+"'")==true){
                   this.jTFRepresentanteLegal.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFRUC.getText()+"'","NOMBRE"));
                   this.jTFDireccion1.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFRUC.getText()+"'","DIRECCION"));
                    this.jTFCelular1.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFRUC.getText()+"'","TELEFONO_CLIENTE"));
                    this.jTFNombre1.setText(conexion.obtenerRegistro("cliente", "ID_CLIENTE = '"+JTFRUC.getText()+"'","Empresa"));
        this.JTFRUC.setEnabled(false);
        this.jTFCelular1.setEnabled(true);
        this.jTFDireccion1.setEnabled(true);
        this.jTFRepresentanteLegal.setEnabled(true);
        this.jBActualizar.setVisible(true);
        this.jBNuevo.setVisible(true);    
        this.jLabel4.setVisible(true);
        this.jBAceptar1.setVisible(false);
                    this.jTFNombre1.setVisible(true);
                    this.jTFNombre1.setEnabled(false);
                                                this.jBActualizar1.setVisible(true);
                            this.jBNuevo1.setVisible(true);
               }else{
               JOptionPane.showMessageDialog(rootPane, "El cliente no existe");
               }
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Se ha ingresado erróneamente el RUC");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "El campo se encuentra vacìo");
     }


    }//GEN-LAST:event_jBAceptar1ActionPerformed

    private void jBActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizar1ActionPerformed
        Pattern pat = Pattern.compile("[0-9]{10}");
     Matcher mat1 = pat.matcher(this.JTFRUC.getText());
     if(jTFCelular1.getText().length()>0 && jTFDireccion1.getText().length()>0 && jTFRepresentanteLegal.getText().length()>0){
           if ( mat1.matches()) {
               if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFRUC.getText()+"'")==true){           
                   conexion.modificarRegistro("Cliente","NOMBRE= '"+jTFRepresentanteLegal.getText()+"' , TELEFONO_CLIENTE= '"+jTFCelular1.getText()+"', DIRECCION = '"+jTFDireccion1.getText()+"'","ID_CLIENTE = '"+JTFCedula.getText()+"'" );
        JOptionPane.showMessageDialog(rootPane, "Informaciòn actualizada");               
               }else{
                        JOptionPane.showMessageDialog(rootPane, "El RUC del cliente ingresado no existe");
               }
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Un dato ha sido ingresado erróneamente");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "Ingrese datos en todos los campos");
     }
    }//GEN-LAST:event_jBActualizar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFIngreso jfing = new JFIngreso();
        jfing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
       if(this.jTFNombre.getText().length()>0 && this.jTFNombre.getText().length()<=30){    
     }else{
                            JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");
         
     }
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDireccionActionPerformed
       if(this.jTFDireccion.getText().length()>0 && this.jTFDireccion.getText().length()<=50){
     }else{
         JOptionPane.showMessageDialog(rootPane, "El número de teléfono ingresado es incorrecto");
     }
    }//GEN-LAST:event_jTFDireccionActionPerformed

    private void jTFNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombre1ActionPerformed
       if(this.jTFNombre1.getText().length()>0 && this.jTFNombre1.getText().length()<=30){    
     }else{
       JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");     
     }    
    }//GEN-LAST:event_jTFNombre1ActionPerformed

    private void jTFRepresentanteLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRepresentanteLegalActionPerformed
        if(this.jTFNombre.getText().length()>0 && this.jTFNombre.getText().length()<=30){    
     }else{
       JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");     
     }  
    }//GEN-LAST:event_jTFRepresentanteLegalActionPerformed

    private void jTFCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCelular1ActionPerformed
        Pattern pat1 = Pattern.compile("^(09)([0-9]){8}");
     Matcher mat1 = pat1.matcher(this.jTFCelular.getText());
     if(mat1.matches()==false){
         JOptionPane.showMessageDialog(rootPane, "El número de teléfono ingresado es incorrecto");
     }  
    }//GEN-LAST:event_jTFCelular1ActionPerformed

    private void jTFDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDireccion1ActionPerformed
        if(this.jTFDireccion.getText().length()>0 && this.jTFDireccion.getText().length()<=50){
     }else{
         JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");
     }
    }//GEN-LAST:event_jTFDireccion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFActualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFCedula;
    private javax.swing.JTextField JTFRUC;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAceptar1;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBActualizar1;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBNuevo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCelular;
    private javax.swing.JTextField jTFCelular1;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFRepresentanteLegal;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
