/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFCliente;

import Fuentes.AlgoritmoVerificar;
import Fuentes.Conexion;
import JFrameLogin.JFIngreso;
import Módulo.JFModuloAdmi;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN
 */
public class JFConsultarCliente extends javax.swing.JFrame {
    private Conexion conexion ;
        private AlgoritmoVerificar av;
    /**
     * Creates new form JFEmpleado
     */
    public JFConsultarCliente() {
                        av = new AlgoritmoVerificar();
                conexion =  new Conexion("Equimeta", "123");
        conexion.crearConexion();
        initComponents();
         this.setLocationRelativeTo(null);
         this.jTFCedula.setVisible(false);
         this.JLCedula.setVisible(false);
         this.jLRUC.setVisible(false);
         this.jTFRUC.setVisible(false);
         this.jBConsultar.setVisible(false);
         this.jLinCli.setVisible(false);
         this.jCBCli.setVisible(false);
        this.jTConsultarCliente.setModel(new DefaultTableModel(0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JLCedula = new javax.swing.JLabel();
        jTFCedula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jBConsultar = new javax.swing.JButton();
        jCBOpciones = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLRUC = new javax.swing.JLabel();
        jTFRUC = new javax.swing.JTextField();
        jLinCli = new javax.swing.JLabel();
        jCBCli = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTConsultarCliente = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MÓDULO CLIENTE");

        jButton4.setText("MÓDULOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        JLCedula.setText("Ingresar número de cédula:");

        jTFCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCedulaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("CONSULTAR CLIENTE");

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        jCBOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar una opción", "Lista de clientes", "Número de Cédula", "RUC" }));
        jCBOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOpcionesActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione una opción:");

        jLRUC.setText("Ingresar RUC:");

        jLinCli.setText("Seleccione el tipo de cliente:");

        jCBCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar una opción", "Cliente Juridico", "Cliente Natural" }));
        jCBCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLinCli)
                            .addComponent(JLCedula)
                            .addComponent(jLRUC))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFCedula)
                            .addComponent(jCBOpciones, 0, 188, Short.MAX_VALUE)
                            .addComponent(jTFRUC)
                            .addComponent(jCBCli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel12)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLinCli)
                            .addComponent(jCBCli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLCedula, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRUC)
                            .addComponent(jTFRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jTConsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTConsultarCliente);

        jMenu1.setText("Menú");

        jMenuItem1.setText("Registrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Actualizar Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Eliminar Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        if( this.jCBOpciones.getSelectedIndex()==3){
        Pattern pat = Pattern.compile("[0-9]{13}");
        Matcher mat = pat.matcher(this.jTFRUC.getText());
        if (mat.matches()) {
            String[] cabecera={"RUC","Representante Legal","Dirección","Teléfono", "Empresa"};
            DefaultTableModel tabla = conexion.consultarTablaCondicionClienteJuridico("CLIENTE", cabecera," ID_CLIENTE = '"+this.jTFRUC.getText()+"'","ID_CLIENTE,NOMBRE,DIRECCION,TELEFONO_CLIENTE,EMPRESA");
            if (tabla.getRowCount()==0){
                System.out.println("Usuario no existe");
                JOptionPane.showMessageDialog(rootPane, "El cliente no existe");
            }else{
                jTConsultarCliente.setModel(tabla);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Se ha ingresado erróneamente el número de RUC: \n"+ this.jTFCedula.getText());
            System.out.println("No Válido");
        }
        this.jTFRUC.setText("");
        }else{
            if(this.jCBOpciones.getSelectedIndex()==2){
        Pattern cat = Pattern.compile("[0-9]{10}");
     Matcher sat = cat.matcher(this.jTFCedula.getText());
     if (sat.matches()) {
         String[] cabecera={"Cédula","Nombre","Dirección","Teléfono"};
         DefaultTableModel tabla = conexion.consultarTablaCondicionClienteNatural("CLIENTE", cabecera," ID_CLIENTE = '"+this.jTFCedula.getText()+"'","ID_CLIENTE,NOMBRE,DIRECCION,TELEFONO_CLIENTE");
         if (tabla.getRowCount()==0){
         System.out.println("Usuario no existe");
             JOptionPane.showMessageDialog(rootPane, "El cliente no existe");
         }else{
         jTConsultarCliente.setModel(tabla);
         }                                                                           
     } else {
         JOptionPane.showMessageDialog(rootPane, "Se ha ingresado erróneamente el número de cédula: \n"+ this.jTFCedula.getText());
         System.out.println("No Válido");                                                                         
     }
     this.jTFCedula.setText("");
        }
        }
            
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFRegistrarCliente jfRegistrar = new JFRegistrarCliente();
        jfRegistrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFActualizarCliente jfActualizar=new JFActualizarCliente();
        jfActualizar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFEliminarCliente jfEliminar = new JFEliminarCliente();
        jfEliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFModuloAdmi jfModulo = new JFModuloAdmi();
        jfModulo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCBOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOpcionesActionPerformed
        switch(this.jCBOpciones.getSelectedIndex()){
            case 0:{
                this.jTFCedula.setVisible(false);
                this.JLCedula.setVisible(false);
                this.jBConsultar.setVisible(false);
                this.jTFRUC.setVisible(false);
                this.jLRUC.setVisible(false);   
                this.jLinCli.setVisible(false);
                this.jCBCli.setVisible(false);
                this.jTConsultarCliente.setModel(new DefaultTableModel(0,0));
                break;
                }
            case 1:{
                this.jTFCedula.setVisible(false);
                this.JLCedula.setVisible(false);
                this.jBConsultar.setVisible(false);
                this.jTFRUC.setVisible(false);
                this.jLRUC.setVisible(false);
                this.jLinCli.setVisible(true);
                 this.jCBCli.setVisible(true);
                break;
            }
            case 2:{
                this.jTFRUC.setVisible(false);
                this.jLRUC.setVisible(false);
                this.jBConsultar.setVisible(true);
                this.jTFCedula.setVisible(true);
                this.JLCedula.setVisible(true);
                this.jLinCli.setVisible(false);
                this.jCBCli.setVisible(false);
                break;
            }
            case 3:{
                this.jLinCli.setVisible(false);
                this.jCBCli.setVisible(false);
                this.jBConsultar.setVisible(true);
                this.jTFCedula.setVisible(false);
                this.JLCedula.setVisible(false);
                this.jTFRUC.setVisible(true);
                this.jLRUC.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_jCBOpcionesActionPerformed

    private void jTFCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCedulaActionPerformed
        if(av.idCardEcuador(this.jTFCedula.getText())==false){
                   JOptionPane.showMessageDialog(rootPane, "El número de cédula ingresado es incorrecto");
                  }
    }//GEN-LAST:event_jTFCedulaActionPerformed

    private void jCBCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCliActionPerformed
         switch(this.jCBCli.getSelectedIndex()){
            case 0:{
                this.jTFCedula.setVisible(false);
                this.JLCedula.setVisible(false);
                this.jBConsultar.setVisible(false);
                this.jTFRUC.setVisible(false);
                this.jLRUC.setVisible(false);   
                this.jLinCli.setVisible(false);
                this.jCBCli.setVisible(false);
                this.jTConsultarCliente.setModel(new DefaultTableModel(0,0));
                break;
                }
            case 1:{
                 String[] cabecera={"RUC","Representante Legal","Dirección","Teléfono", "Empresa"};
                 jTConsultarCliente.setModel(conexion.consultarTablaCondicionCliente("CLIENTE", cabecera, "TIPO = 'JURIDICO' ","ID_CLIENTE,NOMBRE,DIRECCION,TELEFONO_CLIENTE,EMPRESA"));
                break;
            }
            case 2:{
                String[] cabecera={"Cédula","Nombre","Dirección","Teléfono"};
                 jTConsultarCliente.setModel(conexion.consultarTablaCondicionClienteNatural("CLIENTE", cabecera, "TIPO = 'NATURAL' ","ID_CLIENTE,NOMBRE,DIRECCION,TELEFONO_CLIENTE"));
                break;
            }
            
        }
    }//GEN-LAST:event_jCBCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConsultarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLCedula;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCBCli;
    private javax.swing.JComboBox<String> jCBOpciones;
    private javax.swing.JLabel jLRUC;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLinCli;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTConsultarCliente;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFRUC;
    // End of variables declaration//GEN-END:variables
}
