/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFCliente;

import Fuentes.AlgoritmoVerificar;
import Fuentes.Conexion;
import JFrameLogin.JFIngreso;
import Módulo.JFModuloAdmi;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN
 */
public class JFRegistrarCliente extends javax.swing.JFrame {
    private Conexion conexion ;
        private AlgoritmoVerificar av;
    /**
     * Creates new form JFEmpleado
     */
    public JFRegistrarCliente() {
                av = new AlgoritmoVerificar();
         conexion =  new Conexion("Equimeta", "123");
        conexion.crearConexion();
        initComponents();
        this.setLocationRelativeTo(this);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JTFCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFCelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jBRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JTFRUC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFDireccion1 = new javax.swing.JTextField();
        jTFCelular1 = new javax.swing.JTextField();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBRegistrar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTFRepresentanteLegal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MÓDULO CLIENTE");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Número de cédula:");

        JTFCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCedulaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Completo:");

        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jLabel10.setText("Celular:");

        jTFCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCelularActionPerformed(evt);
            }
        });

        jLabel6.setText("Dirección Domiciliaria:");

        jTFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDireccionActionPerformed(evt);
            }
        });

        jBRegistrar.setText("Registrar");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTFNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFCedula, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(83, 83, 83)
                        .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persona Natural", jPanel2);

        jLabel7.setText("RUC:");

        JTFRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFRUCActionPerformed(evt);
            }
        });

        jLabel8.setText("Dirección:");

        jTFDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDireccion1ActionPerformed(evt);
            }
        });

        jTFCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCelular1ActionPerformed(evt);
            }
        });

        jTFNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombre1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Completo de la Empresa:");

        jLabel13.setText("Celular:");

        jBRegistrar1.setText("Registrar");
        jBRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrar1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Representante Legal:");

        jTFRepresentanteLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRepresentanteLegalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(189, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFCelular1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jTFNombre1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFRepresentanteLegal, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTFRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTFRepresentanteLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jBRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTFDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Persona Jurídica", jPanel3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("REGISTRAR CLIENTE");

        jMenu1.setText("Menú");

        jMenuItem2.setText("Actualizar Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Consultar Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Menú Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFConsultarCliente jfConsultar = new JFConsultarCliente();
        jfConsultar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFActualizarCliente jfActualizar=new JFActualizarCliente();
        jfActualizar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFEliminarCliente jfEliminar = new JFEliminarCliente();
        jfEliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void JTFCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCedulaActionPerformed
                  if(av.idCardEcuador(this.JTFCedula.getText())==false){
                    JOptionPane.showMessageDialog(rootPane, "El número de cédula ingresado es incorrecto");
                  }else if (conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFCedula.getText()+"'")){
                      JOptionPane.showMessageDialog(rootPane, "El cliente ya ha sido registrado previamente");
                  }
    }//GEN-LAST:event_JTFCedulaActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
     Pattern pat = Pattern.compile("[0-9]{10}");
     Pattern pat1 = Pattern.compile("^(09)([0-9]){8}");
     Matcher mat = pat.matcher(this.JTFCedula.getText());
     Matcher mat1 = pat1.matcher(this.jTFCelular.getText());
     
     if(jTFCelular.getText().length()>0 && JTFCedula.getText().length()>0 && jTFNombre.getText().length()>0 && jTFDireccion.getText().length()>0){
           if (mat.matches() && mat1.matches()) {
                   conexion.insertarRegistro("Cliente", "'"+this.JTFCedula.getText()+"','"+this.jTFNombre.getText()+"','"+this.jTFDireccion.getText()+"','"+this.jTFCelular.getText()+"', 'NATURAL',null");
                   if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFCedula.getText()+"'")==true){
                        JOptionPane.showMessageDialog(rootPane, "El cliente ha sido registrado exitosamente");
                        this.JTFCedula.setText("");
        this.jTFNombre.setText("");
        this.jTFCelular.setText("");
        this.jTFDireccion.setText("");
        this.JTFCedula.requestFocus();
                   }else{
                        JOptionPane.showMessageDialog(rootPane, "Hemos tenido problemas porfavot vuelva a intentarlo");
                   }
               
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Un dato ha sido ingresado erróneamente");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "Ingrese datos en todos los campos");
     }
          
    }//GEN-LAST:event_jBRegistrarActionPerformed

    private void JTFRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFRUCActionPerformed
        if(this.JTFRUC.getText().length()>0 && this.JTFRUC.getText().length()<13){
        }else{
        JOptionPane.showMessageDialog(rootPane, "El RUC ingresado es incorrecto");
        }
    }//GEN-LAST:event_JTFRUCActionPerformed

    private void jBRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrar1ActionPerformed
        Pattern pat = Pattern.compile("[0-9]{13}||[0-9]{10}");
     Matcher mat = pat.matcher(this.JTFRUC.getText());
     Matcher mat1 = pat.matcher(this.jTFCelular.getText());
     
     if(jTFCelular1.getText().length()>0 && JTFRUC.getText().length()>0 && jTFNombre1.getText().length()>0 && jTFDireccion1.getText().length()>0 && jTFRepresentanteLegal.getText().length()>0){
           if (mat.matches() && mat1.matches()) {
               if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFRUC.getText()+"'")==false){
                   conexion.insertarRegistro("Cliente", "'"+this.JTFRUC.getText()+"','"+this.jTFNombre1.getText()+"','"+this.jTFDireccion1.getText()+"','"+this.jTFCelular1.getText()+"', 'JURIDICO','"+jTFRepresentanteLegal.getText()+"'");
                   if(conexion.existeRegistro("Cliente", "ID_CLIENTE = '"+this.JTFRUC.getText()+"'")==true){
                        JOptionPane.showMessageDialog(rootPane, "El cliente ha sido registrado exitosamente");
                   }else{
                        JOptionPane.showMessageDialog(rootPane, "Hemos tenido problemas porfavot vuelva a intentarlo");
                   }
               }else{
               JOptionPane.showMessageDialog(rootPane, "El cliente ya ha sido registrado previamente");
               }
               
               System.out.println("Válido");                                                                            
     } else {
              JOptionPane.showMessageDialog(rootPane, "Un dato ha sido ingresado erróneamente");                                                                       
     }
         
         
     }else{
     JOptionPane.showMessageDialog(rootPane, "Ingrese datos en todos los campos");
     }
        // TODO add your handling code here:
        this.JTFRUC.setText("");
        this.jTFRepresentanteLegal.setText("");
        this.jTFNombre1.setText("");
        this.jTFCelular1.setText("");
        this.jTFDireccion1.setText("");
        this.JTFRUC.requestFocus();
    }//GEN-LAST:event_jBRegistrar1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFModuloAdmi jfModulo = new JFModuloAdmi();
        jfModulo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
     if(this.jTFNombre.getText().length()>0 && this.jTFNombre.getText().length()<=30){    
     }else{
                            JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");
         
     }
        
        
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCelularActionPerformed
             Pattern pat1 = Pattern.compile("^(09)([0-9]){8}");
     Matcher mat1 = pat1.matcher(this.jTFCelular.getText());
     if(mat1.matches()==false){
         JOptionPane.showMessageDialog(rootPane, "El número de teléfono ingresado es incorrecto");
     }
    }//GEN-LAST:event_jTFCelularActionPerformed

    private void jTFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDireccionActionPerformed
     if(this.jTFDireccion.getText().length()>0 && this.jTFDireccion.getText().length()<=50){
     }else{
         JOptionPane.showMessageDialog(rootPane, "El número de teléfono ingresado es incorrecto");
     }
    }//GEN-LAST:event_jTFDireccionActionPerformed

    private void jTFRepresentanteLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRepresentanteLegalActionPerformed
     if(this.jTFNombre.getText().length()>0 && this.jTFNombre.getText().length()<=30){    
     }else{
       JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");     
     }        
    }//GEN-LAST:event_jTFRepresentanteLegalActionPerformed

    private void jTFNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombre1ActionPerformed
        if(this.jTFNombre1.getText().length()>0 && this.jTFNombre1.getText().length()<=30){    
     }else{
       JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");     
     }   
    }//GEN-LAST:event_jTFNombre1ActionPerformed

    private void jTFCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCelular1ActionPerformed
Pattern pat1 = Pattern.compile("^(09)([0-9]){8}");
     Matcher mat1 = pat1.matcher(this.jTFCelular.getText());
     if(mat1.matches()==false){
         JOptionPane.showMessageDialog(rootPane, "El número de teléfono ingresado es incorrecto");
     }          
    }//GEN-LAST:event_jTFCelular1ActionPerformed

    private void jTFDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDireccion1ActionPerformed
        if(this.jTFDireccion.getText().length()>0 && this.jTFDireccion.getText().length()<=50){
     }else{
         JOptionPane.showMessageDialog(rootPane, "El número de carácteres es excesivo");
     }
    }//GEN-LAST:event_jTFDireccion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFCedula;
    private javax.swing.JTextField JTFRUC;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JButton jBRegistrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCelular;
    private javax.swing.JTextField jTFCelular1;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFRepresentanteLegal;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
